name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: https://github.com/docker/setup-buildx-action@v2

    - name: Login to Gitea Package Registry
      uses: https://github.com/docker/login-action@v2
      with:
        registry: gitea.stendahls.net
        username: oskar.risberg@stendahls.se
        password: ${{ secrets.REGISTRY_PAT }}

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: gitea.stendahls.net/${{ gitea.repository }}
        tags: |
          # set latest tag for default branch
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push
      id: docker_build
      uses: https://github.com/docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}

    - name: Update portainer
      run:  curl -X POST https://portainer.stendahls.dev/api/stacks/webhooks/123b7e66-775f-4432-803a-70a817233233